/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.lhankedev.magicmodel;

import de.lhankedev.magicmodel.exception.MagicModelCreationException;

public interface MagicModelFactory {

    MagicModel createModel(String modelName) throws MagicModelCreationException;

}
