/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.lhankedev.magicmodel;

public interface MagicModelFactory {

    <T> T createModel(String modelName, Class<T> modelClazz);

}
