/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.lhankedev.magicmodel.reflective;

import de.lhankedev.magicmodel.MagicModel;
import de.lhankedev.magicmodel.MagicModelFactory;
import de.lhankedev.magicmodel.assertion.*;
import de.lhankedev.magicmodel.exception.MagicModelCreationException;
import de.lhankedev.magicmodel.model.Car;
import de.lhankedev.magicmodel.model.TerminalTypeTest;
import de.lhankedev.magicmodel.model.directaccess.MobilePhone;
import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.Optional;

class ReflectiveMMFactoryTest {

    private final MagicModelFactory factory = new ReflectiveMMFactory();

    @Test
    void testTerminalSingleValueFields() throws MagicModelCreationException {
        MagicModel magicModel = factory.createModel("TerminalFieldSingleValues");
        Optional<TerminalTypeTest> testTypes = magicModel.getObjectById("testPrimitives", TerminalTypeTest.class);

        Assertions.assertThat(testTypes)
                .isPresent();

        TerminalTypeTestAssertion.assertThat(testTypes.get())
                .hasIntValue(12)
                .hasLongValue(3L)
                .hasBoolValue(true)
                .hasDoubleValue(22.1)
                .hasFloatValue(4.7f)
                .hasStringValue("testString");
    }

    @Test
    void testDirectFieldAccess() throws MagicModelCreationException {
        MagicModel magicModel = factory.createModel("DirectFieldAccess");
        Optional<MobilePhone> phone = magicModel.getObjectById("testPhone", MobilePhone.class);

        Assertions.assertThat(phone)
                .isPresent();

        MobilePhoneAssertion.assertThat(phone.get())
                .hasScreenSize(5.6)
                .hasManufacturer("TestManufacturer")
                .hasWeight(461);
    }

    @Test
    void testTerminalCollectionValueFields() throws MagicModelCreationException {
        MagicModel magicModel = factory.createModel("TerminalFieldCollectionValues");
        Optional<TerminalTypeTest> testTypes = magicModel.getObjectById("testPrimitives", TerminalTypeTest.class);

        Assertions.assertThat(testTypes)
                .isPresent();

        TerminalTypeTestAssertion.assertThat(testTypes.get())
                .hasIntCollection(1, 2)
                .hasLongCollection(3L, 4L)
                .hasBoolCollection(false, true)
                .hasDoubleCollection(1.1, 1.2)
                .hasFloatCollection(1.3f, 1.4f)
                .hasStringCollection("testString1", "testString2");
    }

    @Test
    void testTerminalListValueFields() throws MagicModelCreationException {
        MagicModel magicModel = factory.createModel("TerminalFieldListValues");
        Optional<TerminalTypeTest> testTypes = magicModel.getObjectById("testPrimitives", TerminalTypeTest.class);

        Assertions.assertThat(testTypes)
                .isPresent();

        TerminalTypeTestAssertion.assertThat(testTypes.get())
                .hasIntList(1, 2)
                .hasLongList(3L, 4L)
                .hasBoolList(false, true)
                .hasDoubleList(1.1, 1.2)
                .hasFloatList(1.3f, 1.4f)
                .hasStringList("testString1", "testString2");
    }

    @Test
    void testTerminalSetValueFields() throws MagicModelCreationException {
        MagicModel magicModel = factory.createModel("TerminalFieldSetValues");
        Optional<TerminalTypeTest> testTypes = magicModel.getObjectById("testPrimitives", TerminalTypeTest.class);

        Assertions.assertThat(testTypes)
                .isPresent();

        TerminalTypeTestAssertion.assertThat(testTypes.get())
                .hasIntSet(1, 2)
                .hasLongSet(3L, 4L)
                .hasBoolSet(false, true)
                .hasDoubleSet(1.1, 1.2)
                .hasFloatSet(1.3f, 1.4f)
                .hasStringSet("testString1", "testString2");
    }

    @Test
    void testReferenceInSingleAttribute() throws MagicModelCreationException {
        MagicModel magicModel = factory.createModel("SingleValueReference");
        Optional<Car> car = magicModel.getObjectById("testCar", Car.class);

        Assertions.assertThat(car)
                .isPresent();

        EngineAssertion.assertThat(car.get().getEngine())
                .isNotNull()
                .hasHorsePower(205)
                .hasDisplacement(4009);
    }

    @Test
    void testReferenceInCollectionAttribute() throws MagicModelCreationException {
        MagicModel magicModel = factory.createModel("CollectionValueReference");
        Optional<Car> car = magicModel.getObjectById("testCar", Car.class);

        Assertions.assertThat(car)
                .isPresent();

        PersonsAssertion.assertThat(car.get().getPreviousOwners())
                .hasSize(2)
                .contains("Ele", "Phant", 28)
                .contains("Dino", "Saur", 21);
    }

    @Test
    void testQualifiedParentReference() throws MagicModelCreationException {
        MagicModel magicModel = factory.createModel("QualifiedParentReference");
        Optional<Car> car = magicModel.getObjectById("testCar", Car.class);

        Assertions.assertThat(car)
                .isPresent();

        PersonAssertion.assertThat(car.get().getOwner())
                .isNotNull()
                .hasForeName("Dino")
                .hasLastName("Saur")
                .hasAge(21);
    }

    @Test
    void testImplicitParentReference() throws MagicModelCreationException {
        MagicModel magicModel = factory.createModel("ImplicitParentReference");
        Optional<Car> car = magicModel.getObjectById("testCar", Car.class);

        Assertions.assertThat(car)
                .isPresent();

        EngineAssertion.assertThat(car.get().getEngine())
                .isNotNull()
                .hasHorsePower(205)
                .hasDisplacement(4009);
    }

    @Test
    void testParentCollectionReference() throws MagicModelCreationException {
        MagicModel magicModel = factory.createModel("ParentCollectionReference");
        Optional<Car> car = magicModel.getObjectById("testCar", Car.class);

        Assertions.assertThat(car)
                .isPresent();

        PersonsAssertion.assertThat(car.get().getPreviousOwners())
                .contains("Ele", "Phant", 28)
                .contains("Dino", "Saur", 21);
    }


}
