const val antlrVersion = "4.9"
const val lombokVersion = "1.18.16"
const val reflectionsVersion = "0.9.12"
const val slf4jVersion = "1.7.30"
const val apacheCommonsLangVersion = "3.11"
const val apacheCommonsIoVersion = "2.8.0"
const val mapStructVersion = "1.4.1.Final"
// tests
const val junitVersion = "5.7.0"
const val assertjVersion = "3.6.1"
const val mockitoVersion = "3.6.28"
const val logbackVersion = "1.2.3"