/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.lhankedev.magicmodel.reflective;

import de.lhankedev.magicmodel.MagicModelFactory;
import de.lhankedev.magicmodel.assertion.CarAssertion;
import de.lhankedev.magicmodel.model.Car;
import org.junit.jupiter.api.Test;

class MagicModelFactoryTest {

    private final MagicModelFactory factory = new ReflectiveMMFactory();

    @Test
    void testChildReference() {
        Car car = factory.createModel("CarTestChildReference", Car.class);

        CarAssertion carAssertion = CarAssertion.assertThat(car)
                .isNotNull()
                .hasManufacturer("TestManufacturer")
                .hasModel("TestModel");

        carAssertion.getEngine()
                .isNotNull()
                .hasHorsePower(205)
                .hasDisplacement(4009);

        carAssertion.getOwner()
                .isNotNull()
                .hasForeName("Dino")
                .hasLastName("Saur")
                .hasAge(21);
    }

}
