Modelname: TerminalFieldCollectionValues
Namespace: de.lhankedev.modelpool.model

TerminalTestType(testPrimitives):
    - intCollection:
        - 1
        - 2
    - longCollection:
        - 3
        - 4
    - booleanCollection:
        - false
        - true
    - doubleCollection:
        - 1.1
        - 1.2
    - floatCollection:
        - 1.3
        - 1.4
    - stringCollection:
        - testString1
        - testString2